spring:
  data:
    mongodb:
      uri: your-mongodb-uri
      database: users
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_gmail
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  openai:
    model: model
    api:
      url: https://api.openai.com/v1/chat/completions
      key: your_openai_key
