spring:
  data:
    mongodb:
      uri: your-mongodb-uri
      database: users
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_gmail
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
